# Generated by Django 6.0.4 on 2026-05-03 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_genres', models.JSONField(blank=True, default=list, help_text='List of TMDB genre IDs, e.g. [28, 35, 18]')),
                ('preferred_languages', models.JSONField(blank=True, default=list, help_text='List of ISO 639-1 language codes, e.g. ["en", "ko", "zh"]')),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show'), ('both', 'Both')], default='both', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
