# Generated by Django 6.0.4 on 2026-05-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcheditem',
            name='genre_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of TMDB genre IDs, e.g. [18, 10749]'),
        ),
        migrations.AddField(
            model_name='watcheditem',
            name='original_language',
            field=models.CharField(blank=True, default='', help_text='ISO 639-1 language code, e.g. "en", "ko"', max_length=10),
        ),
    ]
