# Generated by Django 6.0.4 on 2026-05-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_watcheditem_genre_ids_watcheditem_original_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watcheditem',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='watcheditem',
            name='status',
            field=models.CharField(choices=[('watching', 'Currently Watching'), ('completed', 'Completed'), ('plan_to_watch', 'Plan to Watch'), ('on_hold', 'On Hold'), ('dropped', 'Dropped'), ('not_interested', 'Not Interested')], default='completed', help_text='Current watch status', max_length=20),
        ),
        migrations.AddField(
            model_name='watcheditem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
